# 1. Use BellSoft Liberica JDK 17 as the base image
FROM bellsoft/liberica-openjdk-debian:17

# 2. Set the working directory inside the container
WORKDIR /app

# 3. Copy the built jar file from the target directory to the container
# Replace 'myapp.jar' with the actual jar file name generated by your build
COPY target/*.jar /app/app.jar

# 4. Expose the default Spring Boot port (8080)
EXPOSE 8080

# 5. Command to run the jar file
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
